#!/usr/bin/env python3
"""Write the twin's Nav2 parameters: the robot's burger.yaml plus timing slack.

The robot runs Nav2 with turtlebot3_navigation2's ``burger.yaml`` unchanged,
and so does the twin, except for the few timing tolerances below. Each one
exists because the simulator is slower than the robot in a way the robot is
not: Gazebo renders the LiDAR on a CPU-only renderer at a real-time factor of
about 0.7, so a scan reaches Nav2 later in simulation time than it does on the
robot, and every node shares the same cores as the renderer.

Measured on the twin, 2026-10-04 (``docker exec`` read-only probes):

- idle, a scan reaches a subscriber 0.057 s (median) after its stamp;
- with Nav2 driving, the collision monitor logged scans 0.202-0.214 s old and
  stopped the base for an "invalid source" against its 0.2 s source_timeout,
  several times a second;
- bt_navigator aborted a NavigateToPose with "Timed out while waiting for
  action server to acknowledge goal request for follow_path" against its
  20 ms default server timeout.

Only timing keys may be changed here, and the script refuses anything else:
no polygon, speed, footprint, inflation, clearance or robot geometry. The
adapter's own 0.35 m motion clearance floor is not a Nav2 parameter and is not
touched. Usage: ``twin_nav2_params.py SOURCE.yaml OUTPUT.yaml``.
"""

from __future__ import annotations

import copy
import sys
from collections.abc import Mapping
from typing import Any

# Leaf keys an override may set. Each is a wait or a staleness tolerance,
# never a distance, a speed or a shape.
TIMING_KEYS = frozenset(
    {
        "source_timeout",
        "transform_tolerance",
        "default_server_timeout",
        "wait_for_service_timeout",
    }
)

# Never above these, whatever the reason: a source older than this is not a
# reading of the room any more.
CEILINGS = {
    "source_timeout": 1.0,
    "transform_tolerance": 1.0,
    "default_server_timeout": 1000,
    "wait_for_service_timeout": 5000,
}

OVERRIDES: dict[str, Any] = {
    "collision_monitor": {
        "ros__parameters": {
            # Upstream 0.2 s; scans arrive 0.20-0.21 s old under load here.
            "scan": {"source_timeout": 0.5},
        }
    },
    "bt_navigator": {
        "ros__parameters": {
            # Upstream default 20 ms to acknowledge a child action's goal.
            "default_server_timeout": 200,
        }
    },
}


class OverrideError(ValueError):
    """An override that is not a bounded timing tolerance."""


def _check(path: tuple[str, ...], value: Any) -> None:
    key = path[-1]
    if key not in TIMING_KEYS:
        raise OverrideError(f"{'.'.join(path)} is not a timing key the twin may change")
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise OverrideError(f"{'.'.join(path)} must be a number")
    if not 0 < value <= CEILINGS[key]:
        raise OverrideError(f"{'.'.join(path)}={value} is outside (0, {CEILINGS[key]}]")


def apply(params: Mapping[str, Any], overrides: Mapping[str, Any]) -> dict[str, Any]:
    """``params`` with ``overrides`` merged in, refusing non-timing changes.

    An override must name a node and parameter block that already exist, so
    a typo cannot add a parameter nothing reads while the real one stays as
    it was.
    """
    merged = copy.deepcopy(dict(params))

    def merge(target: dict[str, Any], source: Mapping[str, Any], path: tuple[str, ...]):
        for key, value in source.items():
            here = (*path, key)
            if isinstance(value, Mapping):
                existing = target.get(key)
                if not isinstance(existing, dict):
                    raise OverrideError(f"{'.'.join(here)} does not exist in the source")
                merge(existing, value, here)
            else:
                _check(here, value)
                target[key] = value

    merge(merged, overrides, ())
    return merged


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__.strip().splitlines()[-1], file=sys.stderr)
        return 2
    import yaml

    with open(argv[1], encoding="utf-8") as handle:
        params = yaml.safe_load(handle)
    merged = apply(params, OVERRIDES)
    with open(argv[2], "w", encoding="utf-8") as handle:
        handle.write("# Generated by twin_nav2_params.py from " + argv[1] + "\n")
        yaml.safe_dump(merged, handle, sort_keys=False)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
